name: Create Prerelease

on:
  workflow_dispatch:

jobs:
  create_release_branch:
    name: Create Release Branch
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_next_version.outputs.next_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Get next version number
        id: get_next_version
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        # https://github.com/semantic-release/semantic-release/issues/1647#issuecomment-702913849
        run: |
          echo "::set-output name=next_version::v$(npx semantic-release --dryRun --no-ci | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+')-rc"
      - name: Create a release branch with next version number
        run: |
          git checkout -b release/${{steps.get_next_version.outputs.next_version}}
          git push --set-upstream origin release/${{steps.get_next_version.outputs.next_version}}
  create_prerelease:
    name: Create Prerelease
    runs-on: ubuntu-latest
    needs: create_release_branch

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/${{needs.create_release_branch.outputs.version}}

      - name: Create prerelease
        id: create_prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.create_release_branch.outputs.version}}
          release_name: Prerelease ${{needs.create_release_branch.outputs.version}}
          draft: false
          prerelease: true