# Testing workflow for validating if docker-compose works properly

name: Docker Compose test
on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Print all containers
        run: |
          docker ps -a
      - name: Validate if there is a database container running
        run: |
          OUTPUT=$(docker ps --filter "name=web_app_sandbox_db_1")
          ${{ contains("${OUTPUT}", "web_app_sandbox_db_1") }}