# TEsting workflow not showing in repository settings as required status

name: E2E CI Tests
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  workflow_dispatch:

jobs:
  e2e:
    name: E2E CI Tests - job name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
