# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI - Functional Tests

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Google Chrome
      run: |
        chmod +x ./scripts/InstallChrome.sh
         ./scripts/InstallChrome.sh
    - name: Run Functional Tests
      run: mvn -Dtest=dev.hotdeals.treecreate.functional.** test
