# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI - Functional Tests

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Google Chrome
      run: |
        chmod +x ./scripts/installChrome.sh
         ./scripts/installChrome.sh
    - name: Run The Webserver
      run: |
        mvn -B package --file pom.xml
        java -jar target/*.jar &
      env:
        WEBSANDBOX_JDBC_URL: ${{ secrets.WEBSANDBOX_JDBC_URL }}
    - name: Wait 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Run Functional tests
      run: mvn -Dtest=dev.hoteals.web_app_sandbox.functional.** test
