name: Testing workflows

env:
  TEST_VAR: ${{ github.event.release.tag_name }}
  TEST_VAR2: "example 2"
  TEST_VAR3: ${{ github.event.release.tag_name }}

on:
  workflow_dispatch:

jobs:
  test:
    name: Test the env vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test the var
        run: |-
          if [[ -z $TEST_VAR ]]; then
            TEST_VAR="custom var"
          fi

      - name: Test the var 2
        run: |-
          echo "TEST VAR: $TEST_VAR"

      - name: Test the var 3
        run: |-
          if [[ -z $TEST_VAR3 ]]; then
            TEST_VAR3="custom 3"
            echo "TEST var3 was empty"
          else
            echo "TEST var3 was not empty"
          fi
          echo "TEST VAR: $TEST_VAR3"

  test2:
    name: Test more vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test the var
        run: |-
          if [[ -z $TEST_VAR ]]; then
            echo "TEST var was empty, but IO won't set a new one"
          else
            echo "TEST var was not empty"
          fi
          echo "TEST VAR: $TEST_VAR"
