name: Testing workflows

env:
  TEST_VAR: ${{ github.event.release.tag_name }}

on:
  workflow_dispatch:

jobs:
  test:
    name: Build and Publish Docker Image for API in staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test the var
        run: |-
          echo "Test: "$TEST_VAR
